<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="validate_colors_list_tests.py" name="validate_colors_list_tests.TestValidateColorsList-20191012191848" skipped="0" tests="2" time="0.005" timestamp="2019-10-12T19:18:48">
	<testcase classname="validate_colors_list_tests.TestValidateColorsList" file="src/unittest/python/validate_colors_list_tests.py" line="12" name="testInvalidNumberOf3Bands" time="0.005" timestamp="2019-10-12T19:18:48">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="validate_colors_list_tests.TestValidateColorsList" file="src/unittest/python/validate_colors_list_tests.py" line="7" name="testValidColors4Bands" time="0.000" timestamp="2019-10-12T19:18:48">
		<error message="'TestValidateColorsList' object has no attribute 'assertNotRaises'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/home/student/Desktop/SystemProgramming/Projects/NolanWilliamsProject2/src/unittest/python/validate_colors_list_tests.py", line 9, in testValidColors4Bands
    with self.assertNotRaises(ValueError):
AttributeError: 'TestValidateColorsList' object has no attribute 'assertNotRaises'
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
